import { Story, User } from "../types";

export const currentUser: User = {
  id: "user-1",
  name: "여행자",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
  bio: "",
  city: "서울",
  ageGroup: "20대",
  occupation: "스타트업 직장인",
  stickerCount: 12,
};

export const mockUsers: User[] = [
  {
    id: "user-2",
    name: "희망의빛",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    bio: "",
    city: "서울",
    ageGroup: "20대",
    occupation: "취업준비생",
    stickerCount: 8,
  },
  {
    id: "user-3",
    name: "바다",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    bio: "",
    city: "부산",
    ageGroup: "30대",
    occupation: "프리랜서",
    stickerCount: 12,
  },
  {
    id: "user-4",
    name: "새벽",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    bio: "",
    city: "인천",
    ageGroup: "20대",
    occupation: "대학생",
    stickerCount: 15,
  },
];

export const mockStories: Story[] = [
  {
    id: "story-0",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "worry",
    content: "요즘 새로운 프로젝트를 맡게 되면서 부담감이 크다. 팀원들의 기대에 부응할 수 있을지, 제대로 해낼 수 있을지 걱정된다. 하지만 최선을 다해보려고 한다.",
    categories: ["커리어/직장생활"],
    empathyCount: 15,
    empathizedBy: ["user-2"],
    stickers: [
      { userId: "user-3", message: "할 수 있어요!", emoji: "✨" },
    ],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "story-1",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "worry",
    content: "오늘 꿈꿔왔던 스타트업에서 세 번째 면접을 봤다. 기술 질문은 잘 대답한 것 같은데, 조직 문화 적합성 부분이 걱정이다. 장기 목표에 대해 물어봤을 때 머릿속이 하얗게 변했다. 다음 주 계획도 못 세우는데 왜 5년 후 계획을 세우는 게 이렇게 어려운 걸까? 또 기다림의 시간이 시작되네...",
    categories: ["취준/취직"],
    empathyCount: 24,
    empathizedBy: [],
    stickers: [
      { userId: "user-3", message: "할 수 있어요!", emoji: "✨" },
      { userId: "user-2", message: "응원합니다!", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "story-2",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "worry",
    content: "연인과 동거에 대한 '그 대화'를 나눴다. 하고 싶지만 동시에 너무 무섭다. 우리가 맞지 않다는 걸 깨닫게 되면 어쩌지? 내 독립성을 잃으면 어쩌지? 지금 우리가 가진 걸 망치면 어쩌지? 근데 또... 만약 정말 좋으면? 왜 다음 단계로 나아가는 게 절벽에서 뛰어내리는 것처럼 느껴지는 걸까?",
    categories: ["연애/결혼", "인간관계"],
    empathyCount: 42,
    empathizedBy: ["user-1"],
    stickers: [
      { userId: "user-1", message: "함께 있어요", emoji: "🤝" },
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "story-3",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "worry",
    content: "오늘 엄마한테서 전화가 왔다. 왜 한 달 동안 집에 안 왔냐고. 집에 갈 때마다 내가 퇴보하는 것 같다는 걸 어떻게 설명해야 할까? 가족을 사랑하지만, 그들의 기대에 짓눌리지 않고 내가 누군지 알아가기 위한 공간이 필요하다. 내 성장을 우선순위에 두는 게 이기적인 걸까?",
    categories: ["가족관계", "마음의병/콤플렉스"],
    empathyCount: 67,
    empathizedBy: ["user-1"],
    stickers: [
      { userId: "user-1", message: "괜찮아요", emoji: "💚" },
      { userId: "user-2", message: "잘하고 있어요!", emoji: "👏" },
    ],
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: "story-4",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "worry",
    content: "오늘 통장 잔고를 확인하고 익숙한 그 침통한 기분을 느꼈다. 돈은 괜찮게 벌고 있는데, 다 어디로 가는 걸까? 매달 진지하게 저축을 시작하겠다고 다짐하지만, 인생이 일어난다. 자동차 수리비, 친구 생일, 나 자신에 대한 '투자'. 재정적 안정이 언제쯤 환상처럼 느껴지지 않을까?",
    categories: ["경제/금전", "마음의병/콤플렉스"],
    empathyCount: 53,
    empathizedBy: [],
    stickers: [],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: "story-5",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "grateful",
    content: "오늘 카페에서 작업하고 있었는데, 낯선 분이 커피 한 잔을 사주고 가셨다. '힘내세요'라는 메모와 함께. 별것 아닐 수도 있지만 요즘 힘든 시기를 보내고 있었는데 정말 큰 위로가 됐다. 세상에는 여전히 따뜻한 사람들이 많다는 걸 다시 한번 느꼈다.",
    categories: ["인간관계", "일상"],
    empathyCount: 38,
    empathizedBy: [],
    stickers: [
      { userId: "user-4", message: "응원해요!", emoji: "🌟" },
    ],
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
  },
  {
    id: "story-6",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "grateful",
    content: "지난주에 상담을 시작했다. 첫 세션은 압도적이었지만, 드디어 나 자신을 돌보는 첫 걸음을 뗐다는 게 자랑스럽다. 상담사님이 '용기 있는 선택이었다'고 말씀해주셨을 때 눈물이 났다. 나를 위해 시간과 돈을 투자하는 게 이렇게 의미 있는 일인지 몰랐다.",
    categories: ["건강/간병", "마음의병/콤플렉스"],
    empathyCount: 89,
    empathizedBy: ["user-1"],
    stickers: [
      { userId: "user-1", message: "힘을 내요!", emoji: "☀️" },
      { userId: "user-2", message: "잘하고 있어요!", emoji: "👏" },
    ],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "story-7",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "grateful",
    content: "오늘 엄마가 갑자기 집에 반찬을 가져다주셨다. '요즘 바쁘다며? 잘 챙겨 먹어야지'라고 하시면서. 평소에는 잔소리처럼 느껴졌는데 오늘은 정말 감사했다. 이렇게 나를 신경 써주는 사람이 있다는 게 큰 행운이라는 걸 깨달았다.",
    categories: ["가족관계", "일상"],
    empathyCount: 45,
    empathizedBy: ["user-1"],
    stickers: [],
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000),
  },
  {
    id: "story-8",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "worry",
    content: "프리랜서 4년차가 됐지만 여전히 불안정함에 익숙해지지 않는다. 이번 달 프로젝트가 끝나면 다음 일감이 있을까? 안정적인 직장으로 돌아가야 하나? 하지만 자유로운 삶이 좋은데... 이 선택이 맞는 건지 계속 고민된다.",
    categories: ["커리어/직장생활", "경제/금전"],
    empathyCount: 31,
    empathizedBy: ["user-2"],
    stickers: [],
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
  },
  {
    id: "story-9",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "worry",
    content: "회사에서 야근이 일상이 되어버렸다. 팀장님은 '스타트업이니까'라고 하시는데, 내 건강과 삶은 어디로 가는 걸까? 친구들과 약속도 못 잡고, 주말에는 피곤해서 집에서만 있게 된다. 이게 정말 내가 원하던 삶일까?",
    categories: ["커리어/직장생활", "건강/간병"],
    empathyCount: 58,
    empathizedBy: ["user-3", "user-4"],
    stickers: [
      { userId: "user-4", message: "힘내세요!", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 40 * 60 * 60 * 1000),
  },
  {
    id: "story-10",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "worry",
    content: "졸업 학년인데 진로가 막막하다. ��변 친구들은 다 취업 준비하거나 대학원 가는데 나는 아직도 뭘 하고 싶은지 모르겠다. 부모님은 빨리 취직하라고 하시는데... 나만 뒤쳐지는 것 같아서 불안하다.",
    categories: ["학업/시험", "진로"],
    empathyCount: 72,
    empathizedBy: ["user-2"],
    stickers: [
      { userId: "user-2", message: "천천히 가도 괜찮아요", emoji: "🌱" },
    ],
    createdAt: new Date(Date.now() - 45 * 60 * 60 * 1000),
  },
  {
    id: "story-11",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "worry",
    content: "6개월째 취준 중인데 서류에서 계속 떨어진다. 스펙이 부족한 건지, 자소서를 못 쓰는 건지... 친구들은 하나둘 합격 소식 전하는데 나만 제자리인 것 같다. 부모님께 죄송하고 나 자신이 한심하게 느껴진다.",
    categories: ["취준/취직", "마음의병/콤플렉스"],
    empathyCount: 84,
    empathizedBy: ["user-1", "user-4"],
    stickers: [
      { userId: "user-1", message: "응원합니다!", emoji: "✨" },
      { userId: "user-4", message: "포기하지 마세요", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 50 * 60 * 60 * 1000),
  },
  {
    id: "story-12",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "grateful",
    content: "프로젝트가 예상보다 일찍 끝나서 오랜만에 해변을 산책했다. 파도 소리를 들으며 걷다 보니 그동안 놓쳤던 것들이 보였다. 푸른 하늘, 따뜻한 햇살, 여유... 일에 치여 살다가 이런 순간을 만끽할 수 있다는 게 감사하다.",
    categories: ["일상", "건강/간병"],
    empathyCount: 41,
    empathizedBy: ["user-1"],
    stickers: [
      { userId: "user-1", message: "힐링되네요", emoji: "🌊" },
    ],
    createdAt: new Date(Date.now() - 55 * 60 * 60 * 1000),
  },
  {
    id: "story-13",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "grateful",
    content: "팀원이 '요즘 많이 힘들어 보인다'며 조용히 간식을 책상에 놓고 갔다. 말은 없었지만 그 작은 배려가 정말 큰 위로가 됐다. 함께 일하는 사람들이 이렇게 따뜻해서 감사하다.",
    categories: ["커리어/직장생활", "인간관계"],
    empathyCount: 52,
    empathizedBy: ["user-2", "user-3"],
    stickers: [
      { userId: "user-2", message: "좋은 팀이네요!", emoji: "🤝" },
    ],
    createdAt: new Date(Date.now() - 60 * 60 * 60 * 1000),
  },
  {
    id: "story-14",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "worry",
    content: "SNS를 보다가 또 우울해졌다. 다들 행복해 보이는데 나만 힘든 것 같다. 비교하지 말아야지 하면서도 자꾸 남들과 내 삶을 비교하게 된다. 이런 내가 한심하다.",
    categories: ["마음의병/콤플렉스", "인간관계"],
    empathyCount: 95,
    empathizedBy: ["user-1", "user-2", "user-3"],
    stickers: [
      { userId: "user-3", message: "당신도 잘하고 있어요", emoji: "💚" },
    ],
    createdAt: new Date(Date.now() - 65 * 60 * 60 * 1000),
  },
  {
    id: "story-15",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "grateful",
    content: "스터디 그룹 친구가 면접 준비 도와준다고 밤늦게까지 같이 있어줬다. '우리 같이 합격하자'는 말에 눈물이 날 뻔했다. 혼자가 아니라는 게 이렇게 큰 힘이 되는구나.",
    categories: ["취준/취직", "인간관계"],
    empathyCount: 68,
    empathizedBy: ["user-4"],
    stickers: [
      { userId: "user-4", message: "좋은 친구네요!", emoji: "✨" },
    ],
    createdAt: new Date(Date.now() - 70 * 60 * 60 * 1000),
  },
  {
    id: "story-16",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "worry",
    content: "30대 중반인데 아직도 결혼에 대한 압박이 심하다. 명절 때마다 친척들이 '언제 결혼하냐'고 물어보는 게 스트레스다. 나는 지금 혼자여도 행복한데... 왜 결혼을 해야만 완전한 어른이 되는 걸까?",
    categories: ["가족관계", "연애/결혼"],
    empathyCount: 77,
    empathizedBy: ["user-1", "user-2"],
    stickers: [],
    createdAt: new Date(Date.now() - 75 * 60 * 60 * 1000),
  },
  {
    id: "story-17",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "worry",
    content: "오늘 실수로 중요한 데이터를 날릴 뻔했다. 다행히 복구했지만 식은땀이 났다. 회사에서 실수하면 안 된다는 압박감에 항상 긴장하고 있다. 완벽해야 한다는 강박이 나를 너무 힘들게 한다.",
    categories: ["커리어/직장생활", "마음의병/콤플렉스"],
    empathyCount: 46,
    empathizedBy: ["user-4"],
    stickers: [
      { userId: "user-4", message: "실수는 누구나 해요", emoji: "💚" },
    ],
    createdAt: new Date(Date.now() - 80 * 60 * 60 * 1000),
  },
  {
    id: "story-18",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "grateful",
    content: "교수님께서 과제에 '창의적이고 좋은 접근이었다'는 피드백을 주셨다. 한 달 넘게 고민하고 준비한 프로젝트였는데 인정받은 것 같아서 뿌듯하다. 포기하지 않고 끝까지 해낸 나 자신이 자랑스럽다.",
    categories: ["학업/시험"],
    empathyCount: 55,
    empathizedBy: ["user-1", "user-2"],
    stickers: [
      { userId: "user-1", message: "축하해요!", emoji: "🎉" },
      { userId: "user-2", message: "멋져요!", emoji: "👏" },
    ],
    createdAt: new Date(Date.now() - 85 * 60 * 60 * 1000),
  },
  {
    id: "story-19",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "worry",
    content: "집에서 취준하다 보니 하루 종일 아무도 안 만나는 날이 많다. 외롭고 우울하다. 친구들한테 연락하기도 민망하고... 이렇게 사는 게 맞나 싶다.",
    categories: ["마음의병/콤플렉스", "인간관계"],
    empathyCount: 61,
    empathizedBy: ["user-3"],
    stickers: [
      { userId: "user-3", message: "연락 주세요!", emoji: "📱" },
    ],
    createdAt: new Date(Date.now() - 90 * 60 * 60 * 1000),
  },
  {
    id: "story-20",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "grateful",
    content: "클라이언트가 '덕분에 프로젝트가 성공적이었다'며 추가 보너스를 주셨다. 예상치 못한 감사 인사와 보상에 일의 보람을 다시 느꼈다. 내 노력을 알아봐 주는 사람이 있다는 게 감사하다.",
    categories: ["커리어/직장생활", "경제/금전"],
    empathyCount: 44,
    empathizedBy: ["user-1", "user-4"],
    stickers: [
      { userId: "user-1", message: "축하드려요!", emoji: "🎊" },
    ],
    createdAt: new Date(Date.now() - 95 * 60 * 60 * 1000),
  },
  {
    id: "story-21",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "worry",
    content: "주말에도 일 생각이 떠나지 않는다. 쉬면서도 계속 메일 확인하고, 업무 메시지 확인하고... 일과 삶의 경계가 무너진 것 같다. 이대로 가다간 번아웃 올 것 같은데 어떻게 해야 할지 모르겠다.",
    categories: ["커리어/직장생활", "건강/간병"],
    empathyCount: 82,
    empathizedBy: ["user-2", "user-3"],
    stickers: [
      { userId: "user-3", message: "휴식도 일이에요", emoji: "🌱" },
    ],
    createdAt: new Date(Date.now() - 100 * 60 * 60 * 1000),
  },
  {
    id: "story-22",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "worry",
    content: "학자금 대출 상환 생각하면 막막하다. 졸업도 안 했는데 벌써 빚이 천만원이 넘는다. 알바하면서 학교 다니는 게 힘들지만 빚을 더 늘리고 싶지 않다. 왜 공부하는 것도 이렇게 돈이 많이 드는 걸까.",
    categories: ["경제/금전", "학업/시험"],
    empathyCount: 91,
    empathizedBy: ["user-2", "user-3"],
    stickers: [
      { userId: "user-2", message: "함께 힘내요", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 105 * 60 * 60 * 1000),
  },
  {
    id: "story-23",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "grateful",
    content: "도서관에서 공부하다가 같은 취준생과 이야기를 나눴다. '다 잘 될 거예요'라는 말이 위로가 됐다. 모르는 사람인데도 서로 응원하고 격려하는 게 참 따뜻했다.",
    categories: ["취준/취직", "인간관계"],
    empathyCount: 36,
    empathizedBy: ["user-4"],
    stickers: [],
    createdAt: new Date(Date.now() - 110 * 60 * 60 * 1000),
  },
  {
    id: "story-24",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "worry",
    content: "친한 친구가 결혼한다고 한다. 진심으로 축하하지만 동시에 외로움도 느껴진다. 친구들이 하나둘 가정을 꾸리는데 나는 여전히 혼자다. 외롭다고 아무하고나 사귈 수도 없고... 적당한 사람을 만나는 게 왜 이렇게 어려운 걸까.",
    categories: ["연애/결혼", "인간관계"],
    empathyCount: 73,
    empathizedBy: ["user-1"],
    stickers: [
      { userId: "user-1", message: "좋은 사람 만날 거예요", emoji: "🌟" },
    ],
    createdAt: new Date(Date.now() - 115 * 60 * 60 * 1000),
  },
  {
    id: "story-25",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "grateful",
    content: "오늘 프로젝트 발표가 성공적으로 끝났다. 팀원들과 함께 준비한 게 좋은 결과로 이어져서 뿌듯하다. 고생한 만큼 보상받는 느낌이 좋다. 이런 순간을 위해 힘든 시간을 견디는 거구나.",
    categories: ["커리어/직장생활"],
    empathyCount: 49,
    empathizedBy: ["user-2", "user-4"],
    stickers: [
      { userId: "user-2", message: "축하해요!", emoji: "🎉" },
    ],
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000),
  },
  {
    id: "story-26",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "worry",
    content: "과 친구들이 다 취업 준비하거나 대학원 준비하는데 나만 방황하는 것 같다. 학점도 좋지 않고, 스펙도 없고... 무엇부터 시작해야 할지 모르겠다. 시간만 가는 것 같아서 불안하다.",
    categories: ["학업/시험", "진로"],
    empathyCount: 87,
    empathizedBy: ["user-2", "user-3"],
    stickers: [
      { userId: "user-3", message: "천천히 시작해봐요", emoji: "🌱" },
    ],
    createdAt: new Date(Date.now() - 125 * 60 * 60 * 1000),
  },
  {
    id: "story-27",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "grateful",
    content: "오늘 드디어 1차 면접 합격 통보를 받았다! 수십 번 떨어지고 나서 받은 합격 소식이라 더 감격스럽다. 포기하지 않길 잘했다. 다음 면접도 잘 준비해야지!",
    categories: ["취준/취직"],
    empathyCount: 102,
    empathizedBy: ["user-1", "user-3", "user-4"],
    stickers: [
      { userId: "user-1", message: "축하드립니다!", emoji: "🎊" },
      { userId: "user-4", message: "최종까지 화이팅!", emoji: "✨" },
    ],
    createdAt: new Date(Date.now() - 130 * 60 * 60 * 1000),
  },
  {
    id: "story-28",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "grateful",
    content: "오랜만에 고향 친구들을 만났다. 각자 다른 길을 걷고 있지만 여전히 서로를 응원하고 격려하는 모습에 감동했다. 변하지 않는 우정이 있다는 게 참 감사하다.",
    categories: ["인간관계"],
    empathyCount: 57,
    empathizedBy: ["user-1", "user-4"],
    stickers: [
      { userId: "user-4", message: "좋은 친구들이네요!", emoji: "🤝" },
    ],
    createdAt: new Date(Date.now() - 135 * 60 * 60 * 1000),
  },
  {
    id: "story-29",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "worry",
    content: "오늘 상사한테 혼났다. 내 잘못도 있지만 사람들 앞에서 창피를 주는 건 너무한 것 같다. 퇴근하고 나서도 계속 그 장면이 떠올라서 잠을 못 잤다. 회사 가기 싫다.",
    categories: ["커리어/직장생활", "마음의병/콤플렉스"],
    empathyCount: 79,
    empathizedBy: ["user-2", "user-3"],
    stickers: [
      { userId: "user-2", message: "힘내세요", emoji: "💚" },
    ],
    createdAt: new Date(Date.now() - 140 * 60 * 60 * 1000),
  },
  {
    id: "story-30",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "grateful",
    content: "오늘 처음으로 새벽 운동을 시작했다. 아침 공기가 이렇게 상쾌한지 몰랐다. 작은 변화지만 뭔가 새로운 시작을 하는 것 같아서 기분이 좋다. 꾸준히 해봐야지.",
    categories: ["건강/간병"],
    empathyCount: 43,
    empathizedBy: ["user-1", "user-3"],
    stickers: [
      { userId: "user-1", message: "멋져요!", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 145 * 60 * 60 * 1000),
  },
  {
    id: "story-31",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "worry",
    content: "부모님께 용돈 받는 게 너무 미안하다. 빨리 취직해서 효도하고 싶은데... 스스로 벌어서 생활하는 친구들을 보면 부럽기도 하고 나 자신이 한심하게 느껴진다.",
    categories: ["경제/금전", "가족관계"],
    empathyCount: 94,
    empathizedBy: ["user-3", "user-4"],
    stickers: [
      { userId: "user-4", message: "곧 좋은 날이 올 거예요", emoji: "✨" },
    ],
    createdAt: new Date(Date.now() - 150 * 60 * 60 * 1000),
  },
  {
    id: "story-32",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "worry",
    content: "건강검진 결과가 안 좋게 나왔다. 일에만 집중하느라 건강을 소홀히 한 게 후회된다. 이제라도 운동하고 건강 챙겨야 하는데 막상 실천하기가 쉽지 않다.",
    categories: ["건강/간병"],
    empathyCount: 66,
    empathizedBy: ["user-1", "user-2"],
    stickers: [
      { userId: "user-1", message: "건강 챙기세요!", emoji: "💚" },
    ],
    createdAt: new Date(Date.now() - 155 * 60 * 60 * 1000),
  },
  {
    id: "story-33",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "grateful",
    content: "오늘 후배가 '선배님 덕분에 많이 배웠다'고 말해줬다. 나도 배우는 입장인데 누군가에게 도움이 됐다니 뿌듯하다. 서로 배우고 성장하는 관계가 참 좋다.",
    categories: ["커리어/직장생활", "인간관계"],
    empathyCount: 51,
    empathizedBy: ["user-3", "user-4"],
    stickers: [
      { userId: "user-4", message: "멋진 선배네요!", emoji: "👏" },
    ],
    createdAt: new Date(Date.now() - 160 * 60 * 60 * 1000),
  },
  {
    id: "story-34",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "worry",
    content: "동아리 선배들과 비교당하는 게 힘들다. '작년 선배는 이랬는데 너는 왜 그러냐'는 말을 들으면 자존감이 바닥으로 떨어진다. 내 페이스대로 가면 안 되는 걸까?",
    categories: ["학업/시험", "인간관계"],
    empathyCount: 70,
    empathizedBy: ["user-2"],
    stickers: [
      { userId: "user-2", message: "당신만의 길이 있어요", emoji: "🌟" },
    ],
    createdAt: new Date(Date.now() - 165 * 60 * 60 * 1000),
  },
  {
    id: "story-35",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "worry",
    content: "면접에서 또 떨어졌다. '조금 더 경험이 필요하다'는 피드백을 받았는데, 신입인데 어떻게 경험을 쌓으라는 건지 모르겠다. 닭이 먼저냐 달걀이 먼저냐 같은 상황이다.",
    categories: ["취준/취직"],
    empathyCount: 88,
    empathizedBy: ["user-1", "user-4"],
    stickers: [
      { userId: "user-1", message: "포기하지 마세요!", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 170 * 60 * 60 * 1000),
  },
  {
    id: "story-36",
    userId: "user-3",
    userName: "바다",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop",
    userCity: "부산",
    userAgeGroup: "30대",
    userOccupation: "프리랜서",
    feedType: "grateful",
    content: "오늘 오랜만에 가족들과 저녁을 먹었다. 일하느라 바빠서 자주 못 만났는데 함께 시간을 보내니 마음이 따뜻해진다. 가족의 소중함을 다시 느꼈다.",
    categories: ["가족관계"],
    empathyCount: 62,
    empathizedBy: ["user-1", "user-2"],
    stickers: [
      { userId: "user-2", message: "따뜻하네요!", emoji: "💛" },
    ],
    createdAt: new Date(Date.now() - 175 * 60 * 60 * 1000),
  },
  {
    id: "story-37",
    userId: "user-1",
    userName: "여행자",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "스타트업 직장인",
    feedType: "worry",
    content: "회사 사람들과 어울리는 게 힘들다. 다들 친한데 나만 겉도는 것 같다. 점심시간에도 혼자 먹을 때가 많다. 사회생활이 이렇게 어려운 줄 몰랐다.",
    categories: ["커리어/직장생활", "인간관계"],
    empathyCount: 75,
    empathizedBy: ["user-2", "user-4"],
    stickers: [
      { userId: "user-4", message: "천천히 친해질 거예요", emoji: "🤝" },
    ],
    createdAt: new Date(Date.now() - 180 * 60 * 60 * 1000),
  },
  {
    id: "story-38",
    userId: "user-4",
    userName: "새벽",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    userCity: "인천",
    userAgeGroup: "20대",
    userOccupation: "대학생",
    feedType: "grateful",
    content: "교수님께서 추천서를 써주신다고 하셨다. 평소에 열심히 하는 모습을 봐주셨나 보다. 인정받는다는 느낌이 들어서 정말 기쁘다. 더 열심히 해야겠다는 동기부여가 된다.",
    categories: ["학업/시험"],
    empathyCount: 48,
    empathizedBy: ["user-1", "user-2", "user-3"],
    stickers: [
      { userId: "user-2", message: "멋져요!", emoji: "✨" },
    ],
    createdAt: new Date(Date.now() - 185 * 60 * 60 * 1000),
  },
  {
    id: "story-39",
    userId: "user-2",
    userName: "희망의빛",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    userCity: "서울",
    userAgeGroup: "20대",
    userOccupation: "취업준비생",
    feedType: "grateful",
    content: "아르바이트하면서 만난 동료가 '언젠가 좋은 회사 다니는 당신을 볼 거예요'라고 말해줬다. 힘든 시기를 겪고 있는데 이런 응원이 정말 큰 힘이 된다. 꼭 그날이 오길 바란다.",
    categories: ["취준/취직", "인간관계"],
    empathyCount: 69,
    empathizedBy: ["user-3", "user-4"],
    stickers: [
      { userId: "user-3", message: "꼭 그렇게 될 거예요!", emoji: "🌟" },
      { userId: "user-4", message: "응원합니다!", emoji: "💪" },
    ],
    createdAt: new Date(Date.now() - 190 * 60 * 60 * 1000),
  },
];
